# Generated by Django 2.1.4 on 2018-12-12 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizz_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizz_app.Pizza')),
            ],
        ),
    ]
